### ISSUE TITLE
API to bulk-query webmentions for multiple pages

### ISSUE THREAD

**Issue by Seirdy** [zerok/webmentiond#61]
I have a Hugo-powered static site. During builds, Hugo fetches webmentions for each page and generates HTML markup for them.

Unfortunately, this requires querying webmentions for each page (the `target` parameter). As my site gains more pages, the number of requests continues to increase. Right now, every clean-cache build triggers over 100 requests over a couple seconds; my server can handle it, but this eats up most of my build time!

I propose introducing some mechanism by which we can pull webmentions from multiple pages in a headless CI-like environment. Perhaps we could specify multiple targets, or exclude the `target` parameter altogether to simply bulk-query all verified webmentions.

**Comment by zerok** [comment]
Sounds good :) I'll try to find some time for it next week :)

**Comment by Seirdy** [comment]
This could also be really great to query webmentions for URLs containing fragments. That'd be necessary for me to set up marginalia: <https://indieweb.org/marginalia>.

Being able to just "bulk-grab all webmentions for the domain" should facilitate grabbing webmentions with fragment URL targets without having to make N different requests for the same page.

-- 
Seirdy (https://seirdy.one)

**Comment by zerok** [comment]
> This could also be really great to query webmentions for URLs containing fragments. That'd be necessary for me to set up marginalia: <https://indieweb.org/marginalia>. Being able to just "bulk-grab all webmentions for the domain" should facilitate grabbing webmentions with fragment URL targets without having to make N different requests for the same page.
> […](#)
> -- Seirdy (https://seirdy.one)

Let's move that part into a separate ticket for now as they probably related but the implementation would probably affect different aspects of the implementation, I guess 😄 

Regarding the listing of *all* mentions, you could also use the `/manage/mentions` endpoint which gives you paginated access to all mentions. That's the endpoint that the admin UI uses to give you a list of all mentions. Since you need access to that API at built-time and not dynamically, giving your build-script access to the management API might be a slight overkill but a IMO a good workaround.

Sadly, authentication is currently completely e-mail based but we could also create access tokens for the management API somehow. Would that solve your problem?

**Comment by Seirdy** [comment]
Access tokens could work! I just need the ability to bulk-grab all mentions. Doing so would automatically enable support for marginalia (in a sufficiently capable consumer), since "grabbing all mentions" would include mentions with fragments in the target. No additional work would be needed on webmentiond's end.

-- 
Seirdy (https://seirdy.one)

**Comment by zerok** [comment]
Sorry for the silence :) Life happened and I'm still working out some edge cases. But I'm working on it! 🙂

**Comment by zerok** [comment]
@Seirdy : I've just an admin access-keys feature into a feature branch (#65). Could you please try if this solves your issue? 😄

**Comment by Seirdy** [comment]
Thanks for working on this. I'm busy atm, but I'll give it a try this weekend.

**Comment by Seirdy** [comment]
Unfortunately, I've only been getting core-dumps no matter what (or if) I set my CFLAGS/LDFLAGS/GOFLAGS to.

**Comment by Seirdy** [comment]
Ah nevermind; my systemd service was filtering the wrong syscalls. It's live now; I'll give the new API a spin soon.

**Comment by zerok** [comment]
Solved with #65
